language: cpp

matrix:
  include:
    - os: osx

install:
  - brew update
  - brew install qt5
  - brew link --force qt5

script:
  - qmake NXController.pro

before_deploy:
  - /usr/local/Cellar/qt/5.13.1/bin/macdeployqt NXController.app -dmg -verbose=2
  - zip -r NXController-macOS.zip NXController.dmg
