language: cpp

matrix:
  include:
    - os: osx

install:
  - brew update
  - brew install qt5
  - brew link --force qt5

script:
  - qmake NSController.pro

before_deploy:
  - /usr/local/Cellar/qt/5.13.1/bin/macdeployqt NSController.app -dmg -verbose=2
  - zip -r NSController-macOS.zip NSController.dmg
