environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    QTPATH: C:\Qt\5.13\msvc2017_64
    OS: win64
    VCVARSALLPATH: C:\"Program Files (x86)\Microsoft Visual Studio"\2019\Community\VC\Auxiliary\Build\vcvarsall.bat
    VCVARSALL: x64
  - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
    OS: linux
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    QTPATH: C:\Qt\5.13\msvc2017
    OS: win32
    VCVARSALLPATH: C:\"Program Files (x86)\Microsoft Visual Studio"\2019\Community\VC\Auxiliary\Build\vcvarsall.bat
    VCVARSALL: x86

install:
    - git submodule update --init --recursive    
    
before_build:
    # Windows
    - cmd: set PATH=%QTPATH%\bin;C:\Qt\Tools\QtCreator\bin;%PATH%
    - cmd: call %VCVARSALLPATH% %VCVARSALL%
    # Linux
    - sh: sudo apt-get -qq update
    - sh: sudo apt-get install -y build-essential qtbase5-dev qt5-qmake qt5-default libqt5serialport5-dev
    
build_script:
    - qmake NXController.pro
    # Windows
    - cmd: jom -j %NUMBER_OF_PROCESSORS%
    # Linux
    - sh: make -j $(nproc)
    
after_build:
    # Windows
    - cmd: md NXController-windows
    - cmd: move release\NXController.exe NXController-windows\NXController.exe 
    - cmd: windeployqt --release --no-translations --no-angle --no-plugins --no-opengl-sw NXController-windows\NXController.exe
    - cmd: del NXController-windows\vc_redist*.exe
    - cmd: xcopy /I %QTPATH%\plugins\platforms\qwindows.dll NXController-windows\platforms\
    - cmd: xcopy /I %QTPATH%\plugins\styles\qwindowsvistastyle.dll NXController-windows\styles\
    - cmd: 7z a NXController-%OS%.zip NXController-windows\
    # Linux
    - sh: zip -r NXController-linux.zip NXController
    
artifacts:
- path: NXController-%OS%.zip
